name: "Analyze package"

on:
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - "bin/**"
      - "example/**"
      - "lib/**"
      - "test/**"
      - "tool/**"
      - "tools/**"
      - ".github/workflows/package_analyze.yaml"
      - "analysis_options.yaml"
      - "dart_dependency_validator.yaml"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - "bin/**"
      - "example/**"
      - "lib/**"
      - "test/**"
      - "tool/**"
      - "tools/**"
      - ".github/workflows/package_analyze.yaml"
      - "analysis_options.yaml"
      - "dart_dependency_validator.yaml"
      - "pubspec.yaml"

permissions:
  statuses: write
  checks: write

jobs:
  analysis:
    runs-on: [self-hosted, macOS]

    steps:
      - name: Validate semantic changelog update
        if: ${{ github.event_name == 'pull_request' }}
        uses: GetStream/verify-semantic-changelog-update@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: olaparty/flutter-action@main
        with:
          flutter-repo: "git@github.com:olachat/flutter.git"
          channel: "flutter-3.13.9"
          cache: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: dart pub get

      - name: Run dependency validator
        run: |
          dart pub global activate dependency_validator
          dart pub global run dependency_validator:dependency_validator

      - name: Analyze project
        run: dart analyze --fatal-warnings --fatal-infos .

      - name: Analyze by DCM
        uses: olachat/dart-code-metrics-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folders: "bin, example, lib, test"
          pull_request_comment: true
          fatal_warnings: true
          fatal_performance: true
          fatal_style: true
          check_unused_files: true
          check_unused_files_folders: "bin, example, lib"

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - name: Compute the package score on pub.dev site
        uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  testing:
    needs: analysis
    runs-on: [self-hosted, macOS]

    defaults:
      run:
        shell: bash

    steps:
      - uses: olaparty/flutter-action@main
        with:
          flutter-repo: "git@github.com:olachat/flutter.git"
          channel: "flutter-3.13.9"
          cache: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        if: success()
        run: |
          dart test --coverage=coverage --reporter=github --file-reporter="json:reports/tests.json"
          dart run coverage:format_coverage --in coverage --out coverage/coverage.lcov --lcov --report-on=lib
          dart run tool/uncovered_coverage.dart
          dart test test/fake_test.dart --coverage=coverage
          dart run coverage:format_coverage --in coverage --out coverage/coverage.lcov --lcov --report-on=lib
          bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
